### ISSUE TITLE
`ENTSO-E_Test_Configurations_v3.0.2` defects

### ISSUE THREAD

**Issue by VladimirAlexiev** [Sveino/Inst4CIM-KG#134]
hi @HarisVranaj ! You said this dataset is at a closed github project, but I don't know which one.
I'll post any defects I find in this issue:
- ENTSO-E_Test_Configurations_v3.0.2/v3.0/MicroGrid/MicroGrid-Type2/MicroGrid-Type2-HVDC-MAS/20210401T1730Z_1D_HVDC_SV_1.xml: lacks `md:Model.modelingAuthoritySet`. It's the only file with this defect:
```
grep -cr modelingAuthoritySet ../../../CGMES-SHACL/ENTSO-E_Test_Configurations_v3.0.2/v3.0|grep xml:0
../../../CGMES-SHACL/ENTSO-E_Test_Configurations_v3.0.2/v3.0/MicroGrid/MicroGrid-Type2/MicroGrid-Type2-HVDC-MAS/20210401T1730Z_1D_HVDC_SV_1.xml:0
```

**Comment by Sveino** [comment]
Open a ticked in the repository for the test modeless, https://github.com/Sveino/CGMES-TC/issues/26

It should have the same `md:Model.modelingAuthoritySet` as TP, `<md:Model.modelingAuthoritySet>http://HVDC.be/CGMES</md:Model.modelingAuthoritySet> `
