### ISSUE TITLE
replace `eumd:DateTimeStamp` with standard datatype, remove `eu:URI`

### ISSUE THREAD

**Issue by VladimirAlexiev** [Sveino/Inst4CIM-KG#20]
Header-AP-Voc-RDFS2020.ttl defines non-standard datatypes:
```ttl
eu:URI  rdf:type rdfs:Class ; cims:stereotype "European" , "Primitive" .
eumd:DateTimeStamp  rdf:type rdfs:Class ; cims:stereotype  "eumd" , "Primitive" .
```
This is similar to https://github.com/Sveino/Inst4CIM-KG/issues/27, but unlike `profcim` these Primitives are used:
```ttl
md:Model.modelingAuthoritySet cims:dataType eu:URI ;
md:Model.profile cims:dataType eu:URI ;
dcat:startDate cims:dataType eumd:DateTimeStamp
```
It's better to replace with standard prop classes and datatypes:
```ttl
md:Model.modelingAuthoritySet a owl:ObjectProperty.
md:Model.profile a owl:ObjectProperty.
dcat:startDate a owl:DatatypeProperty; rdfs:range xsd:dateTimeStamp.
```

I prefer to represent URLs as real URLs (object props without range) not literals. 
If you prefer literals, use this (but the only benefit of `xsd:anyURI` is that it allows URLs with invalid chars):
```ttl
md:Model.modelingAuthoritySet a owl:DatatypeProperty; rdfs:range xsd:anyURI.
md:Model.profile a owl:DatatypeProperty; rdfs:range xsd:anyURI.
dcat:startDate a owl:DatatypeProperty; rdfs:range xsd:dateTimeStamp.
```

**Comment by Sveino** [comment]
Yes, we should definitely remove eumd:DataTimeStamp and eu.URI. I also prefer the use of  owl:DatatypeProperty;

**Comment by VladimirAlexiev** [comment]
fix02-datatypes-74.ru
