### ISSUE TITLE
represent "deprecated" as owl:deprecated

### ISSUE THREAD

**Issue by VladimirAlexiev** [Sveino/Inst4CIM-KG#24]
Various terms have a stereotype "deprecated", eg
```ttl
dcterms:creator  rdf:type  rdf:Property ;
        rdfs:comment       "... This property is deprecated. Use dcterms:publisher.]." ;
        cims:stereotype    "deprecated" , "dcterms" ;
```
- [x] Represent this in a standard way
```ttl
dcterms:creator
  owl:deprecated true
```
- [x] Then it would also be nice to delete this value from `cims:stereotype`, so it has fewer free-text values.

Here's a count per ontology:
```ttl
grep -c '"deprecated"' *.ttl|grep -v ':0'
EquipmentReliability-AP-Voc-RDFS2020.ttl:1
Header-AP-Voc-RDFS2020.ttl:9
ObjectRegistry-AP-Voc-RDFS2020.ttl:2
```

**Comment by Sveino** [comment]
I like this. Originally it should have the same meaning. However, is this the relevant link to the definition: https://www.w3.org/TR/owl-ref/#Deprecation
This is something we missed in the specification.

**Comment by VladimirAlexiev** [comment]
The up-to-date spec is OWL2: https://www.w3.org/TR/2012/REC-owl2-syntax-20121211/#a_deprecated

This is useful to find OWL2 stuff:  https://www.w3.org/TR/owl2-quick-reference/

- [ ] must also count in CGMES ontologies (above is NC)

**Comment by VladimirAlexiev** [comment]
Updated count:
```
grep -rc '"deprecated"' |grep -v ':0'
CGMES/ttl/61970-600-2_Equipment-AP-Voc-RDFS2020_v3-0-0.ttl:7
CGMES/ttl/61970-600-2_EquipmentBoundary-AP-Voc-RDFS2020_v3-0-0.ttl:2
CGMES/ttl/61970-600-2_Topology-AP-Voc-RDFS2020_v3-0-0.ttl:2
CGMES-NC/ttl/EquipmentReliability-AP-Voc-RDFS2020.ttl:1
CGMES-NC/ttl/ObjectRegistry-AP-Voc-RDFS2020.ttl:2
```
So 13 occurrences.

A query shows this is used on 7 props:
```sparql
PREFIX cims: <http://iec.ch/TC57/1999/rdf-schema-extensions-19990926#>
select * {
  ?p cims:stereotype "deprecated"
}
```
|p|
|-------------------------------------------|
| eu: IdentifiedObject.energyIdentCodeEic   |
| eu: IdentifiedObject.shortName            |
| cim: SVCControlMode                       |
| cim: PhaseTapChangerLinear.xMin           |
| cim: PhaseTapChangerNonLinear.xMin        |
| cim: StaticVarCompensator.sVCControlMode  |
| cim: StaticVarCompensator.voltageSetPoint |

Done in `fix15-deprecated-24.ru`.  
Assigning to @Sveino @griddigit-ci to answer why EIC is deprecated?

**Comment by Sveino** [comment]
We would like to remove eu namespace. We are creating an ObjectRegisry profile that can handle multiple names and identification on the same object. My proposal (but not yet approved) is:
![image](https://github.com/user-attachments/assets/bb950a63-7f59-4af3-b35b-618fcfaabff3)

`eu: IdentifiedObject.energyIdentCodeEic -> cim:Name.name and cim:Name.kind = eIC`

**Comment by VladimirAlexiev** [comment]
- Until this proposal is accepted, how can one record EICs? I think you should deprecate it AFTER the proposal is acceped
- For all deprecated props, please describe the reason for deprecation: in `skos:scopeNote`, or simply in `rdfs:comment`
