### ISSUE TITLE
replace `cims:inverseRoleName` by `owl:inverseOf`

### ISSUE THREAD

**Issue by VladimirAlexiev** [Sveino/Inst4CIM-KG#26]
Each CIM object property has an inverse, eg
```ttl
nc:Terminal.VoltageAngleLimit
        rdf:type              rdf:Property ;
        rdfs:comment          "The voltage angle limit which has this reference angle terminal." ;
        rdfs:domain           cim:Terminal ;
        rdfs:range            nc:VoltageAngleLimit ;
        cims:inverseRoleName  nc:VoltageAngleLimit.AngleReferenceTerminal ;

nc:VoltageAngleLimit.AngleReferenceTerminal
        rdf:type              rdf:Property ;
        rdfs:comment          "The angle reference terminal for the voltage angle limit." ;
        rdfs:domain           nc:VoltageAngleLimit ;
        rdfs:range            cim:Terminal ;
        cims:inverseRoleName  nc:Terminal.VoltageAngleLimit ;
```
But `cims:inverseRoleName` is a non-standard prop, and its name is inaccurate (this is the inverse relation, not its **Name**).
So replace it with the standard prop `owl:inverseOf`.

**Comment by Sveino** [comment]
Yes, This should be done. You can see that we did this for RDFS501ED2 export: https://github.com/Sveino/Inst4CIM-KG/blob/cc8fd16ebcf25980ccc937a8e1c4083bf6229b12/source/CGMES/v3.0/RDFSEd2Beta/RDFS/IEC61970-600-2_CGMES_3_0_0_RDFS_501Ed2CD_EQ.rdf#L1726

**Comment by VladimirAlexiev** [comment]
Yes I saw it in CGMES 3.0.
Do you also plan to do it for NC, or that will stay at v2.3 for now?

**Comment by VladimirAlexiev** [comment]
fix11-inverseOf-26.ru
