### ISSUE TITLE
CIM ApparentPower vs QUDT ComplexPower

### ISSUE THREAD

**Issue by VladimirAlexiev** [Sveino/Inst4CIM-KG#43]
```ttl
cim:ApparentPower  a qudt:QuantityKind ;
  qudt:applicableUnit cim:UnitSymbol.VA;
  skos:broader quantitykind:ComplexPower. # ApparentPower is a sub-concept of ComplexPower
cim:UnitSymbol.VA skos:exactMatch unit:V-A
```
But is it true?
- In QUDT, `unit:V-A` applies to `quantitykind:ComplexPower`
- If you google "ApparentPower vs ComplexPower", you can find electrical textbooks that define them as follows:
  - ComplexPower is the vector sum of real power and reactive power. 
  - ApparentPower is the magnitude of complex power. 
- Despite the name `ComplexPower`: units apply to magnitudes, not to vectors
- QUDT defines `ComplexPower` as "under sinusoidal conditions, is the product of the phasor U representing the voltage between the terminals of a linear two-terminal element or two-terminal circuit and the complex conjugate of the phasor I representing the electric current in the element or circuit"
- CIM defines `ApparentPower` as "Product of the RMS value of the voltage and the RMS value of the current."
- To me (not being an electrical engineer), these definitions are "close enough"

Questions:
- is it `skos:broader` or maybe even `skos:exactMatch`
- Do we need to submit `ApparentPower` as a new QuantityKind to QUDT?

**Comment by VladimirAlexiev** [comment]
QUDT refers to https://www.electropedia.org/iev/iev.nsf/display?openform&ievref=131-11-39,
and has these details (in addition to those above):
```ttl
  qudt:latexDefinition "$\\underline{S} = \\underline{U}\\underline{I^*}$, where $\\underline{U}$ is voltage phasor and $\\underline{I^*}$ is the complex conjugate of the current phasor."^^qudt:LatexString ;
  qudt:latexSymbol "$\\underline{S}$"^^qudt:LatexString ;
```
So it also calls it `S`.
Even though it talks of complex numbers, the unit `V-A` applies to magnitudes, not to vectors.
So it has to be the same thing.

**Comment by VladimirAlexiev** [comment]
Answered in https://github.com/qudt/qudt-public-repo/issues/970: QUDT has `ApparentPower` (I overlooked it). Fixed that section.

**Comment by steveraysteveray** [comment]
By the way, @VladimirAlexiev, this topic happens to be what I used in explaining how we compute qudt:applicableUnit triples. See https://github.com/qudt/qudt-public-repo/wiki/Advanced-User-Guide#4-computing-applicable-units-for-a-quantitykind
