### ISSUE TITLE
discrepancies in namespaces in RDFS2020 CGMES vs NC

### ISSUE THREAD

**Issue by VladimirAlexiev** [Sveino/Inst4CIM-KG#68]
Even limiting to the RDFS2020 style only, there are some discrepancies between CGMES and NC:
```
PREFIX cims: <http://iec.ch/TC57/1999/rdf-schema-extensions-19990926#>
PREFIX cim: <http://iec.ch/TC57/CIM100#>
select * {
    ?prop cims:dataType ?qk1,?qk2
    filter(str(?qk1)<str(?qk2))
} order by ?prop
```
| prop                                  | qk1           | qk2                               |
|---------------------------------------|---------------|-----------------------------------|
| dm:DifferenceModel.forwardDifferences | rdf:Statement | rdf:Statements                    |
| dm:DifferenceModel.preconditions      | rdf:Statement | rdf:Statements                    |
| dm:DifferenceModel.reverseDifferences | rdf:Statement | rdf:Statements                    |
| md:Model.created                      | cim:DateTime  | https://cim.ucaiug.io/ns#DateTime |
| md:Model.description                  | cim:String    | https://cim.ucaiug.io/ns#String   |
| md:Model.modelingAuthoritySet         | eu:URI        | https://cim.ucaiug.io/ns/eu#URI   |
| md:Model.profile                      | eu:URI        | https://cim.ucaiug.io/ns/eu#URI   |
| md:Model.scenarioTime                 | cim:DateTime  | https://cim.ucaiug.io/ns#DateTime |
| md:Model.version                      | cim:Integer   | https://cim.ucaiug.io/ns#String   |

- Use different `cim, eu` namespaces
- Use `rdf:Statement` vs `rdf:Statements` (but neither is correct: https://github.com/Sveino/Inst4CIM-KG/issues/53)

**Comment by VladimirAlexiev** [comment]
Actually this problem goes much deeper:
```sparql
PREFIX cims: <http://iec.ch/TC57/1999/rdf-schema-extensions-19990926#>
PREFIX cim: <http://iec.ch/TC57/CIM100#>
select ?qk (count(*) as ?c) {
    ?prop cims:dataType ?qk
} group by ?qk order by ?qk
```
We can see that most properties are shown twice in two different namespaces, eg:
- 100 https://cim.ucaiug.io/ns#ActivePower
- 73 http://iec.ch/TC57/CIM100#ActivePower 

We can confirm this by looking at the files (I've deleted namespaces that are the same):
```
head -10 CGMES-NC/ttl/AssessedElement-AP-Voc-RDFS2020.ttl
@prefix     cim: <https://cim.ucaiug.io/ns#> .
@prefix      nc: <https://cim4.eu/ns/nc#> .
@prefix profcim: <https://cim.ucaiug.io/ns/prof-cim#> .

$ head -10 CGMES/ttl/IEC61970-600-2_CGMES_3_0_0_RDFS2020_EQ.ttl
@prefix     cim: <http://iec.ch/TC57/CIM100#> .
@prefix    cims: <http://iec.ch/TC57/1999/rdf-schema-extensions-19990926#> .
@prefix      eu: <http://iec.ch/TC57/CIM100-European#> .
```

**Comment by VladimirAlexiev** [comment]
What is the new official version-independent namespace?
Should I rewrite `http://iec.ch/TC57/CIM100# -> https://cim.ucaiug.io/ns#`
etc for all other namespaces currently present in duplicate?

**Comment by VladimirAlexiev** [comment]
#13 says
> This is an expected issue, and will cause confusion if all ontologies are used together:
The CIM and CGMES "business" prefixes are defined twice.
This comes from the RDFSEd2Beta style (used for CGMES) vs RDFS2020 style (used for CGMES NC)

But I didn't expect to see it in RDFS2020 alone.
Needs to be fixed before other more complex SPARQL fixes.

**Comment by Sveino** [comment]
We should "in principle" use https://cim.ucaiug.io/ns#. This is what we should expect in all the NC instance dataset. However, they will come with http://iec.ch/TC57/CIM100# for the instance dataset for CGMES. We are moving towards using https://cim.ucaiug.io/ns#. I see that we have two option:

1. Change the cim namespace from http://iec.ch/TC57/CIM100# -> https://cim.ucaiug.io/ns# and have a pre-process as part of the import of the instance dataset to convert the cim reference from http://iec.ch/TC57/CIM100# -> https://cim.ucaiug.io/ns#
2. use reasoning `<http://iec.ch/TC57/CIM100#> owl:sameAs <https://cim.ucaiug.io/ns#>` .

If (2) works it would be my preference. We have the same issue in regards to CIM16 and CIM17, but this can be solved by only addressing the classes that are different rather than the full namespace.

the same applies in regards to `http://iec.ch/TC57/CIM100-European# -> https://cim.ucaiug.io/ns/eu#`

I will look at this separate:
#Use rdf:Statement vs rdf:Statements (but neither is correct: https://github.com/Sveino/Inst4CIM-KG/issues/53)

**Comment by VladimirAlexiev** [comment]
- I would recommend against (2) (actually `eqivalentClass, equivalentProperty` not `sameAs`), see https://github.com/Sveino/Inst4CIM-KG/issues/70.
- `fix-namespaces.pl` does (1): rewrites CGMES ontology URLs to the new namespaces.
- if that is not acceptable (because of existing instance data), I can complicate the fix queries to look for pairs of namespaces:
`cim, cim1` and `eu, eu1`

**Comment by VladimirAlexiev** [comment]
`fix-namespaces.pl` does these replacements (this is perl):
```perl
s{http://iec.ch/TC57/CIM100#}         {https://cim.ucaiug.io/ns#};
s{http://iec.ch/TC57/CIM100-European#}{https://cim.ucaiug.io/ns/eu#};
s{http://purl.org/dc/terms/#}         {http://purl.org/dc/terms/};
s{dcterms:}                           {dct:}g;
```
If that is not acceptable, I can complicate the fix queries to look for pairs of namespaces: `cim, cim1` and `eu, eu1`. It may be unacceptable because existing data that for some reason we cannot convert to new namespaces:
- SHACL shapes
- instance data (eg Nordic44)

@Sveino and @griddigit-ci please decide and either close this one, or assign it to me to avoid the replacements, and to complicate the fixes.
