### ISSUE TITLE
Change Class and Property Kinds

### ISSUE THREAD

**Issue by VladimirAlexiev** [Sveino/Inst4CIM-KG#75]
The new style changes class and property kinds as follows:
- `rdfs:Class` -> `owl:Class`
- `rdf:Property` -> `owl:DatatypeProperty` (if range is `xsd:*`), `owl:ObjectProperty` otherwise
 
It doesn't mean that we need full OWL reasoning much beyond RDFS.
We are just being more specific about the nature of properties.

**Comment by VladimirAlexiev** [comment]
`fix10-classPropKind.ru` (will commit shortly)

**Comment by Sveino** [comment]
In UML we would talk about attribute and association. For me:
```
attribute -> owl:DatatypeProperty
association -> owl:ObjectProperty
```
However, we do have the case of CIMDatatype and we have compound that in UML is model as attribute. In both cases this should be `owl:ObjectProperty.`
So I think the filtering is correct. It would be good to get a TSV out that we can verify it. We also have the text we can run. All attribute (`owl:DatatypeProperty`) should start with a small letter - the exception is the Compound that should be `owl:Class`

**Comment by VladimirAlexiev** [comment]
@Sveino 
- " a TSV out that we can verify it":  I made a folder "datatypes". datatypes-old is from a previous release (prev dump on "sources") and is a bit bigger. "datatypes-actual" is from the current release. Is that enough, or you also need a list of the object props?
- "All attribute (owl:DatatypeProperty) should start with a small letter" . Should  I check this, or you trust it's true?
