### ISSUE TITLE
bad relative URLs (need BASE or urn:uuid:)

### ISSUE THREAD

**Issue by VladimirAlexiev** [Sveino/Inst4CIM-KG#87]
All XML files use node IDs like `rdf:ID="_f1769b90-9aeb-11e5-91da-b8763fd99c5f"`.
These are fragment URLs relative to the file location.
Because xml:base is not set, they end up as random URLs depending on where the file is placed, eg:
```ttl
<file:///d:/Onto/proj/Nordic44/Instances/CGMES_2_4/Nordic44_CGM_37a_EQ.xml#_393332ba-86c3-4257-b77b-006e41b78a71>
        rdf:type                   cim:OperationalLimitSet ;
        entsoe2:OperationalLimitSet.RateTemperature
                <file:///d:/Onto/proj/Nordic44/Instances/CGMES_2_4/Nordic44_CGM_37a_EQ.xml#_92e7d859-88ee-49ed-8a3e-9a7a1464c196> ;
        cim:IdentifiedObject.description
                "OperationalLimitSet 15 degree Celsius" ;
        cim:IdentifiedObject.name  "OLS_15dg_5101_5103_1" ;
        cim:OperationalLimitSet.Equipment
                <file:///d:/Onto/proj/Nordic44/Instances/CGMES_2_4/Nordic44_CGM_37a_EQ.xml#_f1769bc0-9aeb-11e5-91da-b8763fd99c5f> .
```

**Comment by Sveino** [comment]
We are planning to move away from rdf:ID and only use rdf:about. However, I also think that we need to address the issue of xml:base. My thinking is that we can use the URL from modelingAuthoritySet for xml:base.

**Comment by Sveino** [comment]
I think it make sense to think of xml:base as "who is speaking" so for power system model we should use MAS, but for the RDFS it should / could be the IEC standardisation speaking so this could be the CIM namespace.

**Comment by VladimirAlexiev** [comment]
@griddigit @Sveino what is MAS?
Please give examples of the two cases you describe, then I can advise.

**Comment by VladimirAlexiev** [comment]
- @griddigit-ci "CIM namespace or the MAS": The CIM namespaces are well defined. This issue is about instance nodes. 
- URL policy considerations: https://github.com/Sveino/Inst4CIM-KG/issues/98
- Closed by: https://github.com/Sveino/Inst4CIM-KG/issues/94

**Comment by VladimirAlexiev** [comment]
See https://github.com/Sveino/Inst4CIM-KG/tree/develop/rdf-improved/test/trig for examples.
