### ISSUE TITLE
add lang to definitions, remove lang from labels

### ISSUE THREAD

**Issue by VladimirAlexiev** [Sveino/Inst4CIM-KG#93]
CIM terms are defined like this:
```ttl
cim:AsynchronousMachineUserDefined a owl:Class ;
  rdfs:label "AsynchronousMachineUserDefined"@en ;
  rdfs:comment "Asynchronous machine whose dynamic behaviour is described by a user-defined model." ;
```
The label has lang tag, the comment doesn't.
I think it should be the other way around:
- `label` equals the local name of the term's URL, and that won't be translated. If it was written as a phrase "Asynchronous Machine User Defined", I agree with the lang tag. But as written, I'd say it should not have a lang tag
- `comment` is an English sentence, so should have a lang tag

Related to https://github.com/Sveino/Inst4CIM-KG/issues/73

**Comment by Sveino** [comment]
Yes, this is a mistake. In ED2 we used `skos:definition` rather than `rdfs:comment` I like the idea of clearly state that something is a definition rather than just a comment. What do you think?

**Comment by VladimirAlexiev** [comment]
Ontologies have traditionally used `rdfs:comment` for definitions.
Taxonomies use `skos:definition` and not just for Concepts, but some also use it for ConceptScheme.
I think you should keep `rdfs:comment`; and can use extra SKOS props (eg `skos:scopeNote`) for additional aspects.

**Comment by VladimirAlexiev** [comment]
`fix16-langTagLabelVsDefinition.ru`
