### ISSUE TITLE
make custom CIM XML parser

### ISSUE THREAD

**Issue by VladimirAlexiev** [Sveino/Inst4CIM-KG#94]
To do https://github.com/Sveino/Inst4CIM-KG/issues/53, we need to:
- Change the ontology (eg Model won't have rdf:Statements but should be a subclass of `xxx:Graph`)
- Implement a custom CIM XML parser that groks `parseType="Statements"` and emits named graphs

I made such a thing: https://github.com/Sveino/Inst4CIM-KG/blob/develop/rdf-improved/cim-trig.pl
- adds base = MAS
- removes the pesky `_` from node URLs
- adds named graphs; works on `FullModel` and `DifferentialModel`
- is a bit brittle because it manipulates strings not XML, see comments at start of file
- still not documented

See results: https://github.com/Sveino/Inst4CIM-KG/tree/develop/rdf-improved/test/trig
@Sveino @griddigit-ci do you like it, should something be improved?

**Comment by VladimirAlexiev** [comment]
@Sveino I think the model metadata should also be in the model graph: 
else you can't delete a model completely because if its metadata is in the default graph, it will be intermingled with all other models.

**Comment by VladimirAlexiev** [comment]
Moved metadata into the graph. Now it looks like
- FullGrid_OP_diff.trig
```ttl
<urn:uuid:05edbf91-231f-4386-97c0-d4cb498d0afc> { # model metadata
<urn:uuid:05edbf91-231f-4386-97c0-d4cb498d0afc> a dm:DifferenceModel ;
  dm:forwardDifferences <urn:uri:63528ef9-48ff-469b-a58e-ba274f2a10bb> ;
  dm:reverseDifferences <urn:uri:27c8a164-c656-4712-994a-0ab7cec4fd34> ;
  md:Model.DependentOn <urn:uuid:0cd6ada4-b6dc-4a36-a98c-877a39168cd3> ;
  md:Model.Supersedes <urn:uuid:52a409c9-72d8-4b5f-bf72-9a22ec9353f7> ;
  md:Model.created "2021-11-19T23:16:27Z" ;
}

<urn:uri:27c8a164-c656-4712-994a-0ab7cec4fd34> { # reverseDifferences
<http://fullgrid.eu/CGMES/3.0#87478acb-cd1f-40a6-b4a7-59ec99f8b063> cim:IdentifiedObject.description "SET_PNT_1" .
<http://fullgrid.eu/CGMES/3.0#fc908c16-468f-4a64-ba74-6f57175e0005> cim:AnalogLimit.value "99" .
}

<urn:uri:63528ef9-48ff-469b-a58e-ba274f2a10bb> { # forwardDifferences
<http://fullgrid.eu/CGMES/3.0#87478acb-cd1f-40a6-b4a7-59ec99f8b063> cim:IdentifiedObject.description "SET_PNT_1 test" .
<http://fullgrid.eu/CGMES/3.0#fc908c16-468f-4a64-ba74-6f57175e0005> cim:AnalogLimit.value "100" .
}
```
- FullGrid_OP.trig
```ttl
<urn:uuid:52a409c9-72d8-4b5f-bf72-9a22ec9353f7> { # model graph

<http://fullgrid.eu/CGMES/3.0#_13dacabf-aa4c-4a78-806e-c7c4c6949718> a cim:Discrete ;
  cim:Discrete.ValueAliasSet <http://fullgrid.eu/CGMES/3.0#1a457323-2094-440f-8d30-dc93adf0cdb3> ;
...
<urn:uuid:52a409c9-72d8-4b5f-bf72-9a22ec9353f7> a md:FullModel ;
  md:Model.DependentOn <urn:uuid:0cd6ada4-b6dc-4a36-a98c-877a39168cd3> ;
  md:Model.created "2020-12-10T00:21:43Z" ;
}
```

**Comment by VladimirAlexiev** [comment]
Closing and I seek `approve`

**Comment by VladimirAlexiev** [comment]
Please comment on
> removes the pesky `_` from node URLs

- @Sveino commented the reason is that `rdf:ID` cannot start with digit. But there's no need to use this construct: `rdf:about` does the same job and doesn't have such a restriction
- I think I've seen a node with two `__` so I think it's safer not to have any

**Comment by Sveino** [comment]
It is better to replace "_" with "urn:uuid" that change rdf:ID and rdf:about. We have tried to use this as indented back in 2000... We use rdf:ID in the EQ instance file and then rdf:about in any of the other profile based instance file to tell the receiver that you should already have the object. In the EQ you might or you might not have the object before. Even if we start using the DIFF we might need to exchange a full model as part of Schema upgrade (CIM17 to CIM18), major re-modelling and sync. For JSON-LD we do not have this difference.

So I am OK that this:
```XML

<http://fullgrid.eu/CGMES/3.0#_13dacabf-aa4c-4a78-806e-c7c4c6949718> a cim:Discrete ;
  cim:Discrete.ValueAliasSet <http://fullgrid.eu/CGMES/3.0#1a457323-2094-440f-8d30-dc93adf0cdb3> ;
```
Can be converted to:
```XML

<urn:uuid:13dacabf-aa4c-4a78-806e-c7c4c6949718> a cim:Discrete ;
  cim:Discrete.ValueAliasSet <urn:uuid:1a457323-2094-440f-8d30-dc93adf0cdb3> ;
```
or we go for the way we would like it to be for JSON-LD
with a base that is http://model4powersystem.eu/Statnett

@VladimirAlexiev do base need to be the same for all the releated instance files or could/should it be named graph. If the later then it could be: 
```XML
@base <http://model4powersystem.eu/Statnett-EQOP/> .
```
For the header we have added the concept of MAS though the use of the following properties
```XML

<dcat:isVersionOf rdf:resource="https://energy.referencedata.eu/Model/Statnett-EQOP"/>
<dcat:keyword>RA</dcat:keyword>
<dcterms:publisher rdf:resource="https://energy.referencedata.eu/EIC/10X1001A1001A38Y"/>
<dcterms:references rdf:resource="urn:uuid:99ae9f41-0a91-4d21-a483-7398c160da96"/>
<dcterms:spatial rdf:resource="https://energy.referencedata.eu/Frame/NO-Power-Transmission-System"/>
	
```
`dcterms:references` is refering to the instance dataset that is a named graph. This could be:

```XML

<dcterms:references rdf:resource="http://model4powersystem.eu/Statnett-EQCO/urn:uuid:99ae9f41-0a91-4d21-a483-7398c160da96"/>
	
```
